name: Supabase Keep Alive

on:
  schedule:
    - cron: "0 0 * * 0,2,5" # runs every Sunday, Tuesday, and Friday
  workflow_dispatch:

jobs:
  send-http-request:
    runs-on: ubuntu-latest

    steps:
      - name: Send HTTP Request
        run: curl -L https://exifoo.com/api/supabase-keep-alive
